# Generated by Django 2.0.7 on 2020-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilientcapitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpNasdaq200DmaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('sp500', models.FloatField()),
                ('dma200', models.FloatField()),
            ],
        ),
    ]
